lidar_perception_node:
  ros__parameters:
    LIDAR_PERCEPTION:
      CLUSTER_THRESHOLD1:  0.2
      MIN_CLUSTER_SIZE1: 10
      MAX_CLUSTER_SIZE1: 200

      CLUSTER_THRESHOLD2:  0.8
      MIN_CLUSTER_SIZE2: 10
      MAX_CLUSTER_SIZE2: 20000

      CLUSTER_THRESHOLD3: 1.5
      MIN_CLUSTER_SIZE3: 3
      MAX_CLUSTER_SIZE3: 20000